### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by GuusDeKroon** [leo60228/HueSaber#1]
No matter how many times i try, my hue lights won't change.

I really want to make this work, and from what I can see the poster did a great job.

When I click on my hue bridge, then walk to my headset and click, nothing happens. Also when i click and then click on my Hue bridge nothing happends.

What should I do?

**Comment by leo60228** [comment]
I just saw this issue. Could you try adding `--verbose` to your launch options and seeing if there's any HueSaber-related errors?

**Comment by leo60228** [comment]
You can also add the `fpfc` option to control the menus with your mouse.

**Comment by leo60228** [comment]
You also have your room set as an entertainment area in the Hue app settings, correct?

**Comment by leo60228** [comment]
I'm closing this issue. I'll reopen it once logs are provided, but I'm not able to fix it without them.

**Comment by leo60228** [comment]
I believe that this issue has been fixed with the reupload of 1.1.0. Please re-open it if this is not the case.

**Comment by Neededchicken38** [comment]
Yes I have a entertainment area set up

**Comment by leo60228** [comment]
@Neededchicken38 Please redownload the latest zip for 1.1.0. The zip you have downloaded should be over 1MB.

**Comment by leo60228** [comment]
@Neededchicken38 @GuusDeKroon I've reuploaded 1.1.0 as 1.1.0-reupload to avoid caching issues. Please try this zip. https://github.com/leo60228/HueSaber/releases/download/1.1.0-reupload/HueSaber-Full-fixed.zip

**Comment by GuusDeKroon** [comment]
Thnx!

**Comment by leo60228** [comment]
@GuusDeKroon Did it work?

**Comment by GuusDeKroon** [comment]
Yeah, it did. It works great.

Only thing you could improve is performance, the rest is amazing!
